**MATRIKS PERSEGI**

In [2]:
import numpy as np

a = np.array([[1,2,8],
              [3,4,7],
              [5,6,9]])
print(a)



[[1 2 8]
 [3 4 7]
 [5 6 9]]


**MATRIKS IDENTITAS**

In [4]:
I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**MATRIKS NOL**

In [6]:
Z = np.zeros((3,3))
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


**MATRIKS DIAGONAL**

In [8]:
D = np.diag([5,3,4])
print(D)

[[5 0 0]
 [0 3 0]
 [0 0 4]]


**MATRIKS SKALAR**

In [10]:
import numpy as np

def scalar_matrix(a, b):
    return b * np.identity(a)

scalars = scalar_matrix(3,5)
print(f'Matriks Skalar:\n{scalars}')

Matriks Skalar:
[[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]]


**MATRIKS SIMETRIS**

In [11]:
S = np.array([[1,2],[2,1]])
print(S)

[[1 2]
 [2 1]]


**MATRIKS SEGITIGA ATAS**

In [12]:
def create_upper_triangular_matrix(matrix):
    return np.triu(matrix)

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
uppertriu = create_upper_triangular_matrix(a)
print(uppertriu)

[[1 2 3]
 [0 5 6]
 [0 0 9]]


**MATRIKS SEGITIGA BAWAH**

In [13]:
def create_upper_triangular_matrix(matrix):
    return np.tril(matrix)

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
uppertriu = create_upper_triangular_matrix(a)
print(uppertriu)

[[1 0 0]
 [4 5 0]
 [7 8 9]]


**TRANSPOSE MATRIKS**

In [15]:
A = np.array([[1,2,3],[4,5,6]])
A_T = A.T
print(A_T)

[[1 4]
 [2 5]
 [3 6]]


**PENJUMLAHAN MATRIKS**

In [16]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])
C = A + B

**PERKALIAN MATRIKS-VEKTOR**

In [18]:
A = np.array([[1,2],[4,5]])
B = np.array([5,6])
result = A.dot(B)

TRANSFORMASI GEOMETRI

**TRANSLASI**

In [19]:
def translate(point,tx,ty):
    translation = np.array([[1,0,tx],
                            [0,1,ty],
                            [0,0,1]])
    point = np.append(point,1)
    new_point = translation.dot(point)
    return new_point[:2]

point = np.array([1,2])
translated_point = translate(point,3,4)
print(translated_point)

[4 6]


In [5]:
import numpy as np

A = np.array([[1,2,5],
              [3,4,6]])
B = np.array([[5,6],
              [7,8],
              [9,10]])

C = np.dot(B,A)

print(C)

[[ 23  34  61]
 [ 31  46  83]
 [ 39  58 105]]


In [17]:
def f(x):
    A = np.array([
        [1,2,3],
        [3,4,5]])
    return np.dot(A,x)

def g(x):
    B = np.array([
        [5,6],
        [7,8],
        [9,10]])
    return np.dot(B,x)

def h(x):
    return f(g(x))

x = np.array([2,2])
print(h(x))

[196 376]


In [19]:
from scipy.linalg import qr

A = np.array([[1,2],
              [3,4]])
Q, R = qr(A)

print("Matrix Q:")
print(Q)
print("Matrix R:")
print(R)

Matrix Q:
[[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
Matrix R:
[[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]


***Determinan***

In [8]:
import numpy as np

# Matrix 2X2

A = np.arange(1,5).reshape(2,2)
det_A = np.linalg.det(A)
print(f"Determinn Matrix 2x2 A: {det_A}")

# Matrix 3x3

B = np.arange(1,10).reshape(3,3)
det_B = np.linalg.det(B)
print(f"Determinn Matrix 3x3 B: {det_B}")

Determinn Matrix 2x2 A: -2.0000000000000004
Determinn Matrix 3x3 B: 0.0


In [9]:
C = np.arange(1,17).reshape(4,4)
det_C = np.linalg.det(C)
print(f"Determinan Matriks NxN C : {det_C}")

Determinan Matriks NxN C : 0.0
