In [7]:
import sympy
import numpy as np
vektors = [ np.array([
    [0,5,0],
    [0,-10,0]
]), np.array([
    [5,2],
    [4,1]
]), np.array([
    [2,4,3],
    [4,8,6]
])]
i = 0
for vektor in vektors:
  i += 1
  print(f"Vektor {i}")
  print (vektor)
  _, indexes = sympy.Matrix(vektor).T.rref()
  print(indexes)
  if len(indexes) == 2:
    print('Linearly Independent\n')
  else:
    print('Linearly Dependent\n')

Vektor 1
[[  0   5   0]
 [  0 -10   0]]
(1,)
Linearly Dependent

Vektor 2
[[5 2]
 [4 1]]
(0, 1)
Linearly Independent

Vektor 3
[[2 4 3]
 [4 8 6]]
(0,)
Linearly Dependent



In [8]:
import sympy

# Define the matrix
vektor = [[2, 4, 3],
          [4, 8, 6]]

# Perform row reduction and get the pivot columns
_, indexes = sympy.Matrix(vektor).T.rref()

# Print the pivot columns
print("Pivot columns:", indexes)

# Check if there are 2 pivot columns (implying linear independence)
if len(indexes) == 2:
    print('Linearly Independent')
else:
    print('Linearly Dependent')

Pivot columns: (0,)
Linearly Dependent
